lib/streams/layerMappingStream.js
lib/streams/peliasDocGenerator.js
lib/tasks/import.js
test/data/expected.json
test/streams/layerMappingStreamTest.js
test/units.js

This PR adds a new stream that looks at the Geonames [feature code](http://www.geonames.org/export/codes.html) to properly set the layer of Geonames records. Right now it only supports mapping to the following layers:
* region (states in the USA)
* county
* locality
If anyone has suggestions for feature codes that map to other layers, let me know, as they're quite easy to add.
Fixes #31

Map feature codes to layers

---

lib/streams/featureCodeFilterStream.js
lib/tasks/import.js
package.json
test/data/expected.json
test/streams/featureCodeFilterStream.js
test/units.js

Filter out Geonames feature codes that correspond to historical, destroyed, and other records not useful for geocoding.
Fixes #42

Filter unwanted fcodes

---

lib/streams/layerMappingStream.js
test/streams/layerMappingStreamTest.js

Last week we discovered that Geonames admin regions are not consistent globally (mostly because this may be impossible for any admin heirarchy system), but they appear to be ok within a single country.
I looked at the macroregions in Great Britain, Spain, Italy, and France, and they had a 1 to 1 mapping to a single admin code in each country. This PR sets up a framework where we can define a partial mapping in any country going forward.
This, combined with pelias/api#461, will allow us to have the right label for Wales!
Fixes #49

Add country specific mappings

---

lib/streams/overrideLookedUpLocalityAndLocaladmin.js
lib/tasks/import.js
test/data/expected.json
test/streams/overrideLookedUpLocalityAndLocaladmin.js
test/units.js

Fixed #92 
This PR uses the geonames record `name` value instead of the wof-admin-lookup values when layer is either `locality` or `localadmin`.

override `locality` and `localadmin` values from admin lookup

---

lib/streams/layerMappingStream.js

We were missing ADM3 in the layer mapping which caused a lot of localities to show up as venues: 88181 to be exact! 😿 
Fixes #119

fix: add missing ADM3 tag to layer mapping

---

.jshintrc
lib/tasks/download.js
package.json

The downloader is now similar to the WOF downloader in that it uses
child_process.exec and curl to download data. This seems to be more
reliable than using request and piping to a file.
There were also issues with the progress bar package not showing progress properly, so rather than
sort them out, this allows us to simply remove that package
This change probably will help fix #26, but it's not 100% certain.

Rewrite downloader

---

bin/verify.js
lib/tasks/resolvers.js
package.json

This adds a PR to verify the data downloaded for Geonames. Sometimes these zip files are incomplete or corrupt in a way that prevents the `unzipper` NPM module from reading them. By reading the zip file into a stream that does nothing, we should be able to catch them.

Add verify script

---

README.md

README was using the old way of specifying adminLookup configuration

fixed documentation on adminLookup

---

Dockerfile
README.md

The mystery of metadata from https://github.com/pelias/geonames/issues/222 has been solved! It turns out npm postinstall hooks, which we use to download the metadata, do not fire when `DEBIAN_FRONTEND=noninteractive` is set in the shell, such as we do in our Docker [baseimage](https://github.com/pelias/dockerfiles/blob/master/baseimage/Dockerfile#L8).
This explains why the metadata downloads fine on local machines and in the Chef Mapzen Search environment, but not in Kubernetes. It also doesn't work in the Docker image in general.
This PR adds an explicit `npm run download_metadata` to the Dockerfile, so that the Docker images contain this metadata, solving any Docker or Kubernetes issues.
Additionally, it updates the readme to both clarify the situation in the metadata documentation …

Explicitly handle metadata in Docker and update Documentation

---

bin/functional
bin/units
package.json

The way we were running our unit tests does not catch fatal errors in the unit test run, even though they return non-zero status codes.
By using a dedicated script to run the tests, with the `pipefail` option, we can catch them.
Connects https://github.com/pelias/pelias/issues/744

feat(test): Use test dedicated script to catch errors

---

lib/streams/layerMappingStream.js
test/streams/layerMappingStreamTest.js

RGN should not be mapped
I used Who's On First hierarchy.
ADM4 can be either a localadmin or a locality, for now it will be locality.

fix(featureCodeToLayerFR): Better layer mapping for France

---

.circleci/config.yml
.travis.yml
README.md
package.json

Several changes regarding CI and Node.js versions
- The Docker build script now requires `bash`
- Support for Node.js 6 has been dropped (https://github.com/pelias/pelias/issues/752)
- Semantic-release was running (doing nothing but taking up build time) on all pull requests for no reason
- Readme is updated to point to a central version requirement document rather than listing the supported Node.js version
- Releases now run off the master branch (https://github.com/pelias/pelias/issues/749)

CI and Node.js updates

---

lib/streams/overrideLookedUpLocalityAndLocaladmin.js
lib/streams/peliasDocGenerator.js
package.json
test/data/expected.json
test/streams/peliasDocGeneratorTest.js

Some geonames data has names which are delimited by characters such as `/` `#` or `,`.
This PR splits up the names, recording the additional names as aliases.
eg. `Bern/Berne/Berna` `geonames:locality:7285212`

handle delimited names

---

lib/streams/featureCodeFilterStream.js

These records seem to correspond to large, non-administrative, regions such as 'Northern Europe' and 'Southern California'. They feel very subjective and don't map well into administrative hierarchies, often coming up in unexpected search results.
There are only about 2200 and after a brief skim it looks safe to remove them all.
Fixes https://github.com/pelias/geonames/issues/70

feat(filter): Remove RGN records

---

lib/tasks/import.js
package.json

This allows distinguishing which logger output lines correspond to which
importer during an import.
Connects https://github.com/pelias/dbclient/issues/101

feat(logger): Use dbclient name functionality

---

package.json
test/importTest.js
test/streams/layerMappingStreamTest.js
test/streams/overrideLookedUpLocalityAndLocaladmin.js
test/streams/peliasDocGeneratorTest.js

Replacing event-stream with stream-mock as discussed in pelias/pelias#801
_Can you double check `importTest.js`? I am not sure the test is correct to begin with_
Edit: found the proble, just had to run functional tests

tests(streams) change event-stream to stream-mock

---

package.json
test/data/expected.json

As of `pelias-config@4.8.0`, the default Elasticsearch type name is now `_doc`, which is the value compatible with Elasticsearch 7.
This PR updates the Geonames functional tests to expect that new value.
Connects https://github.com/pelias/config/pull/122
Connects https://github.com/pelias/pelias/issues/831
Fixes https://github.com/pelias/geonames/issues/378

chore(tests): Update test expectations for new doc type name

---

lib/tasks/download.js

The Geonames downloader did not ensure the download directory was created before attempting to download data. This caused issues especially with our docker projects, as the directory would generally not exist.
Fixes https://github.com/pelias/geonames/issues/357
Fixes https://github.com/pelias/docker/issues/82

fix(download): Make download directory before downloading

---

Dockerfile

These scripts will try to run the `downloadMetadata` task before the code actually exists in the Docker image.
We explicitly run that step later, so it's not a problem to skip it during `npm install`

Fix Docker build by skipping npm install scripts

---

Dockerfile

It turns out the fix for downloading metadata in the Docker images from https://github.com/pelias/geonames/pull/398 did _not_ work.
We need to allow NPM scripts during `npm install` so that, among other things, better-sqlite3 can install its Node.js bindings.
In the long run, I wonder if we should rethink the entire metadata approach. Surely it makes sense to treat it as part of the regular download process like we do the `inventory.json` file for the WOF download. That would make a lot of things conceptually easier, and remove one of the key "special" parts of this importer, bringing it more in line with all the others.
But for the short term I wanted to fix the issue without making any changes to peoples workflows or any significant code changes.
So this PR adds _just_ enough files to …

Support metadata download durng `npm install`

---

lib/streams/layerMappingStream.js
test/streams/layerMappingStreamTest.js

Our current deduplication logic prefers https://www.geonames.org/4566967/puerto-rico.html over https://www.geonames.org/4566966/puerto-rico.html
This is likely due to *both* being classified as a 'venue'.
This PR maps the `PCLD` feature code to `dependency` (previously there was no mapping to `dependency`)
```bash
grep PCLD allCountries.txt | cut -f1,2
3573511	Anguilla
661882	Ahvenanmaan Lääni
3573345	Bermuda
3371123	Bouvet Island
1547376	Territory of Cocos (Keeling) Islands
2078138	Territory of Christmas Island
3474414	Falkland Islands
2622320	Faroe Islands
3381670	Guyane
2411586	Gibraltar
3425505	Greenland
3579143	Guadeloupe
3474415	South Georgia and the South Sandwich Islands
4043988	Guam
1547314	Territory of Heard Island and McDonald Islands
1282588	British Indian Ocean Territory …
```

feat(layers): map PCLD feature code to dependency

---

lib/streams/layerMappingStream.js
test/streams/layerMappingStreamTest.js

following on from https://github.com/pelias/geonames/pull/402, the PCLIX feature code also maps to `dependency`.
resolves https://github.com/pelias/geonames/issues/48

feat(layers): map PCLIX feature code to dependency

---

lib/tasks/meta.js
package.json

as mentioned in https://github.com/pelias/geonames/issues/404#issuecomment-1055506176 there seems to be a weird bug with how the geonames metatadata files are encoding comments, (I think!)
using this custom comment handler stream we're able to work around the issue, although I'm still not clear why the `comment` option from https://csv.js.org/parse/options/ (and `sed '/^#/d'`) doesn't do the same thing 🤷 
I've also taken the opportunity to do some simple housekeeping tasks:
- upgrade `csv-parse` module
- enabled `bom` option for `csv-parse` as we have done in other modules
- remove the `mkdirp` module introduced in https://github.com/pelias/geonames/pull/185, since that time we've consolidated on Docker and Windows has made progress in its terminal utilities, I hope it's no longer …

improved handling of CSV comments
